name: Python CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    # ci-workflows v1.0.0-initial
    uses: img2threejs/ci-workflows/.github/workflows/python-ci.yml@66e4071913652d7ce9e0ad66709a5e4e66497e0d
    with:
      python-version: "3.10"
      test-command: python3 -m unittest discover -s forge/tests
